name: Mocha test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v1
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: npm install, build, and test
      run: |
        npm install
        npm install mocha -g
        mocha hello.spec.js
      env:
        CI: true
>>>>>>> fb08f887c9450690c1dfbe9faa7b0563a0f2f7b3
